# Job Application Helper - Docker Compose Configuration
# Multi-container setup for backend and frontend services using UV

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: job-helper-backend
    ports:
      - "8000:8000"
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount sentence-transformers cache for model persistence
      - sentence_transformers_cache:/home/appuser/.cache/torch/sentence_transformers
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8000
      # Set sentence-transformers cache directory
      - TRANSFORMERS_CACHE=/home/appuser/.cache/torch/sentence_transformers
      # Enable encryption (will auto-generate key if not provided)
      - ENABLE_ENCRYPTION=true
      # Use Docker secret for encryption key if provided
      - ENCRYPTION_KEY_FILE=/run/secrets/encryption_key
      # Data paths
      - DATA_DIR=/app/data
      - DOCUMENTS_PATH=/app/data/documents
      - CACHE_PATH=/app/data/cache
      # Ollama configuration (point to local Ollama for GPU support)
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      - OLLAMA_TIMEOUT=300
    depends_on: []
    networks:
      - job-helper-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    secrets:
      - encryption_key

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
    container_name: job-helper-frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - job-helper-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ollama:
    image: ollama/ollama:latest
    platform: linux/arm64
    container_name: job-helper-ollama
    ports:
      - "11434:11434"
    volumes:
      # Persist Ollama models and data
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_GPU_LAYERS=35
    # Comment out Ollama service for local development with GPU
    # Uncomment the ollama service below if you want to use Docker CPU-only Ollama
    profiles: ["docker-ollama"]
    networks:
      - job-helper-network
    restart: unless-stopped


networks:
  job-helper-network:
    driver: bridge
    name: job-helper-network

volumes:
  job-helper-data:
    driver: local
    name: job-helper-data
  sentence_transformers_cache:
    driver: local
    name: sentence-transformers-cache
  ollama_data:
    driver: local
    name: ollama-data

# Secrets are optional - if not provided, the app will auto-generate encryption keys
# To use custom encryption keys, create backend/.secrets/encryption_key file
# Note: Remove the secrets section below if you don't want to use Docker secrets
secrets:
  encryption_key:
    file: ./backend/.secrets/encryption_key
