version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.uv
    container_name: job_helper_backend_uv
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "uv", "run", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - job_helper_network

networks:
  job_helper_network:
    driver: bridge

volumes:
  backend_data:
    driver: local
